{
 "title": "Automate Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "automate_url",
    "label": "Automate Instance URL (i.e. https://automate.yourmsp.com)",
    "query": "${VAR_AUTOMATE_URL}"
   }
  ]
 },
 "panels": [
  { "title": "Automate Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "New Servers Offline Today",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as `Offline in last day`\n\nFROM (((DatabaseFails JOIN Computers USING (ComputerID)) JOIN Agents USING (AgentID)) JOIN Clients ON Clients.ClientID=Computers.ClientID) JOIN Locations ON Locations.LocationID=Computers.LocationID \n\nWHERE Agents.CheckAction=0 AND Agents.Comparor <> 17 AND  Agents.Name Like 'LT - Offline Servers'\n\nAND TIMESTAMPDIFF(Minute, Computers.LastContact, NOW()) < 1440\n"
    }
   ]
  },
  {
   "title": "New Servers Offline This Week",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as `Offline in Last Week`\n\nFROM (((DatabaseFails JOIN Computers USING (ComputerID)) JOIN Agents USING (AgentID)) JOIN Clients ON Clients.ClientID=Computers.ClientID) JOIN Locations ON Locations.LocationID=Computers.LocationID \n\nWHERE Agents.CheckAction=0 AND Agents.Comparor <> 17 AND  Agents.Name Like 'LT - Offline Servers'\n\nAND TIMESTAMPDIFF(Minute, Computers.LastContact, NOW()) < 10080"
    }
   ]
  },
  {
   "title": "Offline Servers (Red is Latest)",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT Clients.Name as `Client`, Computers.Name as `Server`, Computers.ComputerID as `Computer ID`, REPLACE(Computers.LastContact, '', ''), TIMESTAMPDIFF(Minute, Computers.LastContact, NOW()) as `Time Offline`, IFNULL(IFNULL(edfAssigned1.Value,edfDefault1.value),'') as `Service Plan`\n\nFROM (((DatabaseFails JOIN Computers USING (ComputerID)) JOIN Agents USING (AgentID)) JOIN Clients ON Clients.ClientID=Computers.ClientID) JOIN Locations ON Locations.LocationID=Computers.LocationID \nLEFT JOIN ExtraFieldData edfAssigned1 ON (edfAssigned1.id=Locations.LocationId and edfAssigned1.ExtraFieldId =(Select ExtraField.id FROM ExtraField WHERE LTGuid='5ca92306-2d93-11e1-ac0f-3d76979114ae'))\nLEFT JOIN ExtraFieldData edfDefault1 ON (edfDefault1.id=0 and edfDefault1.ExtraFieldId =(Select ExtraField.id FROM ExtraField WHERE LTGuid='5ca92306-2d93-11e1-ac0f-3d76979114ae'))\n\nWHERE Agents.CheckAction=0 AND Agents.Comparor <> 17 AND  Agents.Name Like 'LT - Offline Servers'\n\nORDER BY Computers.LastContact DESC"
    }
   ]
  },
  {
   "title": "Total Offline Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as `Total Offline Servers`\n\nFROM (((DatabaseFails JOIN Computers USING (ComputerID)) JOIN Agents USING (AgentID)) JOIN Clients ON Clients.ClientID=Computers.ClientID) JOIN Locations ON Locations.LocationID=Computers.LocationID \n\nWHERE Agents.CheckAction=0 AND Agents.Comparor <> 17 AND  Agents.Name Like 'LT - Offline Servers'\n"
    }
   ]
  },
  {
   "title": "Low Disk Space",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \n   computers.computerid as `Computer Id`,\n   computers.name as `Server`,\n   clients.name as `Client`,\n   computers.domain as `Computer Domain`,\n   computers.username as `Computer User`,\n   Drives.Letter as `Computer.Drives.Letter`,\n   FLOOR(Drives.Size/1024) as `Computer.Drives.Size.GB`,\n   FLOOR(Drives.Free/1024) as `Computer.Drives.Free.GB`,\n   IFNULL(ROUND((Drives.Size-Drives.Free)/Drives.Size*100,0),0) as `Computer.Drives.Used.Percent`,\n   IFNULL(ROUND(100-(Drives.Size-Drives.Free)/Drives.Size*100,0),0) as `Computer.Drives.Free.Percent`,\n   IF(INSTR(computers.os, 'server')>0, 1, 0) as `Computer.OS.IsServer`,\n   CASE WHEN LEFT(Drives.SmartStatus, INSTR(Drives.SmartStatus, ':')-1) IN('CD', 'DVD') THEN 3 WHEN LEFT(Drives.SmartStatus, INSTR(Drives.SmartStatus, ':')-1) = 'USB' THEN 2 WHEN LEFT(Drives.SmartStatus, INSTR(Drives.SmartStatus, ':')-1) IN('IDE', 'SCSI') THEN 1 WHEN Drives.FileSystem IN('NTFS', 'FAT32', 'FAT', 'HFS', 'ext2', 'ext3', 'ext4', 'btrfs', 'jfs', 'xfs', 'reiser4', 'reiserfs') THEN IF(INSTR(LOWER(Drives.Model), 'usb')>0, 2, 1) ELSE 4 END as `Computer.Drives.Type`\nFROM Computers \nLEFT JOIN inv_operatingsystem ON (Computers.ComputerId=inv_operatingsystem.ComputerId)\nLEFT JOIN Clients ON (Computers.ClientId=Clients.ClientId)\nLEFT JOIN Locations ON (Computers.LocationId=Locations.LocationID)\nLEFT JOIN Drives ON (Drives.ComputerId=Computers.ComputerId)\n WHERE \n((((IF(INSTR(Computers.OS, 'server')>0, 1, 0) <> 0) AND (Drives.Letter like '%') AND (FLOOR(Drives.Size/1024) > 32) AND (IFNULL(ROUND((Drives.Size-Drives.Free)/Drives.Size*100,0),0) >= 75) AND (CASE WHEN LEFT(Drives.SmartStatus, INSTR(Drives.SmartStatus, ':')-1) IN('CD', 'DVD') THEN 3 WHEN LEFT(Drives.SmartStatus, INSTR(Drives.SmartStatus, ':')-1) = 'USB' THEN 2 WHEN LEFT(Drives.SmartStatus, INSTR(Drives.SmartStatus, ':')-1) IN('IDE', 'SCSI') THEN 1 WHEN Drives.FileSystem IN('NTFS', 'FAT32', 'FAT', 'HFS', 'ext2', 'ext3', 'ext4', 'btrfs', 'jfs', 'xfs', 'reiser4', 'reiserfs') THEN IF(INSTR(LOWER(Drives.Model), 'usb')>0, 2, 1) ELSE 4 END <> '3'))))\nORDER BY IFNULL(ROUND(100-(Drives.Size-Drives.Free)/Drives.Size*100,0),0), FLOOR(Drives.Free/1024)"
    }
   ]
  }
 ]
}